### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by euotiniel** [hqasmei/portfolio#5]
If you want to be able to control your website's metrics and you have your portfolio hosted on vercel, you can add ```web analytics```. 

I've recently added:

![Imagem WhatsApp 2024-02-21 às 18 22 53_dbc33a00](https://github.com/hqasmei/portfolio/assets/93485038/4e06a8e0-7ab0-48cb-97a8-6002ed4de280)

You can also see the countries they access the most, browsers, and even the OS.

**Comment by iamitpal** [comment]
she is using beam analytics instead
